version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i npm@latest -g
      - npm cache clean --force --prefix client
      - rm -rf node_modules package-lock.json --prefix client
      - npm install --unsafe-perm --prefix client
      - npm install babel-cli cross-env webpack-cli --global
  build:
    commands:
      - npm run build --prefix client
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
cache:
  paths:
    - "./node_modules/**/*"
