version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --unsafe-perm
      - npm install babel-cli cross-env webpack-cli --global
  build:
    commands:
      - /client npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
cache:
  paths:
    - "/codebuild/output/src521971997/src/node_modules/**/*"
